# Generated by Django 3.1.4 on 2021-01-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('team', models.TextField()),
                ('bc', models.FloatField()),
                ('npxg', models.FloatField()),
                ('xg', models.FloatField()),
                ('bcc', models.FloatField()),
                ('xa', models.FloatField()),
                ('date', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('team', models.TextField()),
                ('role', models.TextField()),
                ('goal', models.FloatField()),
                ('assist', models.FloatField()),
                ('cs', models.FloatField()),
                ('bc', models.FloatField()),
                ('npxg', models.FloatField()),
                ('xg', models.FloatField()),
                ('bcc', models.FloatField()),
                ('xa', models.FloatField()),
                ('sixty', models.FloatField()),
                ('ninety', models.FloatField()),
                ('total_goals', models.IntegerField()),
                ('total_pen', models.IntegerField()),
                ('total_pas', models.IntegerField()),
                ('total_yellow', models.IntegerField()),
                ('total_red', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('team', models.TextField()),
                ('role', models.TextField()),
                ('goal', models.FloatField()),
                ('assist', models.FloatField()),
                ('cs', models.FloatField()),
                ('date', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('sixty', models.FloatField()),
                ('ninety', models.FloatField()),
                ('total_goals', models.IntegerField()),
                ('total_pen', models.IntegerField()),
                ('total_pas', models.IntegerField()),
                ('total_yellow', models.IntegerField()),
                ('total_red', models.IntegerField()),
                ('date', models.TextField()),
            ],
        ),
    ]
